import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Loader from "@/components/custom/loader/loader";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SyncCrowd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      layout: {
        // socialButtonsVariant: "iconButton",
        logoImageUrl: "/synclogo.jpg",
      }
    }}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
